# Generated by Django 2.2.7 on 2019-11-16 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_firstname', models.CharField(max_length=200, verbose_name='prénom')),
                ('user_lastname', models.CharField(max_length=200, verbose_name='nom')),
                ('user_email', models.EmailField(max_length=70, unique=True, verbose_name='email')),
                ('user_password', models.CharField(max_length=50, verbose_name='password')),
                ('user_birthdate', models.DateField(verbose_name="date d'anniversaire")),
                ('user_created_on', models.DateField(default=datetime.date.today, verbose_name='date de création compte')),
                ('user_last_login', models.DateField(default=datetime.date.today, verbose_name='login')),
                ('user_is_active', models.BooleanField(default=False, verbose_name='is active')),
            ],
        ),
    ]
