# Generated by Django 2.2.7 on 2019-11-17 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platformRestaurant', '0002_auto_20191117_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_description',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_informations_pratiques',
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_google', models.CharField(max_length=800, verbose_name='password')),
                ('informations', models.TextField(blank=True, max_length=512, null=True, verbose_name='description')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platformRestaurant.Room')),
            ],
        ),
    ]
